CREATE TABLE IF NOT EXISTS "users" (
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(100) NOT NULL,
	"email" VARCHAR(150) NOT NULL UNIQUE,
	"password" VARCHAR(255) NOT NULL,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "roles" (
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"code" VARCHAR(30) NOT NULL UNIQUE,
	"name" VARCHAR(100) NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "user_roles" (
	"user_id" BIGINT NOT NULL,
	"role_id" SMALLINT NOT NULL,
	PRIMARY KEY("user_id", "role_id")
);

CREATE TABLE IF NOT EXISTS "coordinations" (
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"code" VARCHAR(20) NOT NULL UNIQUE,
	"name" VARCHAR(100) NOT NULL,
	"description" TEXT,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "report_types" (
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"coordination_id" SMALLINT NOT NULL,
	"code" VARCHAR(50) NOT NULL,
	"name" VARCHAR(150) NOT NULL,
	PRIMARY KEY("id")
);

CREATE UNIQUE INDEX "uq_report_types_coord_code"
ON "report_types" ("coordination_id", "code");

CREATE TABLE IF NOT EXISTS "municipalities" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"identity_territory_id" SMALLINT NOT NULL,
	"name" VARCHAR(100) NOT NULL,
	"state_code" VARCHAR(2) NOT NULL DEFAULT 'BA',
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	PRIMARY KEY("id")
);

CREATE UNIQUE INDEX "uq_municipalities_name_state"
ON "municipalities" ("name", "state_code");

CREATE TABLE IF NOT EXISTS "forces" (
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"code" VARCHAR(20) NOT NULL UNIQUE,
	"name" VARCHAR(100) NOT NULL,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "identity_territories" (
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(150) NOT NULL UNIQUE,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "sizes" (
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(20) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "report_series" (
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"created_by" BIGINT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "reports" (
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"report_series_id" BIGINT NOT NULL,
	"report_type_id" SMALLINT NOT NULL,
	"previous_report_id" BIGINT,
	"revision_number" SMALLINT NOT NULL DEFAULT 0,
	"municipality_id" INTEGER,
	"force_id" SMALLINT,
	"size_id" SMALLINT,
	"typology" VARCHAR(100),
	"sei_number" VARCHAR(80),
	"inspection_date" DATE,
	"present_collaborators" VARCHAR(1000),
	"objective" TEXT,
	"land_address" VARCHAR(255),
	"land_zip_code" VARCHAR(10),
	"google_maps_url" VARCHAR(500),
	"distance_from_ssp_km" DECIMAL(10,2),
	"descriptive_memorial" TEXT,
	"land_area_m2" DECIMAL(12,2),
	"land_perimeter_m" DECIMAL(12,2),
	"descriptive_memorial_notes" TEXT,
	"topography" VARCHAR(255),
	"soil_type" VARCHAR(255),
	"drainage" VARCHAR(255),
	"existing_vegetation" VARCHAR(255),
	"infrastructure_water_network" SMALLINT,
	"infrastructure_high_voltage_network" SMALLINT,
	"infrastructure_low_voltage_network" SMALLINT,
	"infrastructure_sewage_network" SMALLINT,
	"infrastructure_telephony" SMALLINT,
	"infrastructure_public_lighting" SMALLINT,
	"infrastructure_internet" SMALLINT,
	"infrastructure_waste_collection" SMALLINT,
	"infrastructure_paving" SMALLINT,
	"infrastructure_existing_buildings" SMALLINT,
	"existing_structures_condition" TEXT,
	"conclusion" TEXT,
	"checklist_sei_construction_request" SMALLINT,
	"checklist_sei_land_and_typology_identification" SMALLINT,
	"checklist_state_owned_land" SMALLINT,
	"checklist_simov_legalized" SMALLINT,
	"checklist_compatible_dimensions" SMALLINT,
	"checklist_slope_or_level_risk" SMALLINT,
	"checklist_stormwater_drainage" SMALLINT,
	"checklist_flood_history" SMALLINT,
	"checklist_electricity_supply" SMALLINT,
	"checklist_water_supply" SMALLINT,
	"checklist_sewage_supply" SMALLINT,
	"checklist_paving_and_sidewalk" SMALLINT,
	"checklist_regular_waste_collection" SMALLINT,
	"checklist_demolition_required" SMALLINT,
	"checklist_easy_public_access" SMALLINT,
	"checklist_domain_strip_or_non_buildable_area" SMALLINT,
	"checklist_technical_feasibility_report" SMALLINT,
	"checklist_report_attached_to_sei" SMALLINT,
	"checklist_works_dashboard_updated" SMALLINT,
	"checklist_environmental_protection_area" SMALLINT,
	"created_by" BIGINT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE UNIQUE INDEX "uq_reports_series_revision"
ON "reports" ("report_series_id", "revision_number");
CREATE INDEX "idx_reports_created_at"
ON "reports" ("created_at");
CREATE INDEX "idx_reports_updated_at"
ON "reports" ("updated_at");
CREATE INDEX "idx_reports_report_type"
ON "reports" ("report_type_id");
CREATE INDEX "idx_reports_municipality"
ON "reports" ("municipality_id");

CREATE TABLE IF NOT EXISTS "report_images" (
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"report_id" BIGINT NOT NULL,
	"uploaded_by" BIGINT NOT NULL,
	"type" VARCHAR(50) NOT NULL,
	"original_name" VARCHAR(255) NOT NULL,
	"storage_path" VARCHAR(500) NOT NULL,
	"mime_type" VARCHAR(100) NOT NULL,
	"size_bytes" BIGINT NOT NULL,
	"file_hash" VARCHAR(64) NOT NULL,
	"caption" VARCHAR(500),
	"position" SMALLINT,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE UNIQUE INDEX "uq_report_images_report_hash"
ON "report_images" ("report_id", "file_hash");
CREATE INDEX "idx_report_images_report"
ON "report_images" ("report_id");

CREATE TABLE IF NOT EXISTS "report_reviews" (
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"report_id" BIGINT NOT NULL,
	"reviewer_id" BIGINT NOT NULL,
	"status" VARCHAR(30) NOT NULL,
	"comment" TEXT,
	"reviewed_at" TIMESTAMP,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE INDEX "idx_report_reviews_report"
ON "report_reviews" ("report_id");
CREATE INDEX "idx_report_reviews_reviewer"
ON "report_reviews" ("reviewer_id");
CREATE INDEX "idx_report_reviews_report_created"
ON "report_reviews" ("report_id", "created_at");

CREATE TABLE IF NOT EXISTS "report_attachments" (
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"report_id" BIGINT NOT NULL,
	"uploaded_by" BIGINT NOT NULL,
	"type" VARCHAR(50) NOT NULL,
	"original_name" VARCHAR(255) NOT NULL,
	"storage_path" VARCHAR(500) NOT NULL,
	"mime_type" VARCHAR(100) NOT NULL,
	"size_bytes" BIGINT NOT NULL,
	"file_hash" VARCHAR(64) NOT NULL,
	"description" VARCHAR(500),
	"position" SMALLINT,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE UNIQUE INDEX "uq_report_attachments_report_hash"
ON "report_attachments" ("report_id", "file_hash");
CREATE INDEX "idx_report_attachments_report"
ON "report_attachments" ("report_id");

ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "user_roles"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "roles"
ADD FOREIGN KEY("id") REFERENCES "user_roles"("role_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "coordinations"
ADD FOREIGN KEY("id") REFERENCES "report_types"("coordination_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "identity_territories"
ADD FOREIGN KEY("id") REFERENCES "municipalities"("identity_territory_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "report_series"("created_by")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "report_series"
ADD FOREIGN KEY("id") REFERENCES "reports"("report_series_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "report_types"
ADD FOREIGN KEY("id") REFERENCES "reports"("report_type_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "reports"("created_by")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "reports"
ADD FOREIGN KEY("id") REFERENCES "reports"("previous_report_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "reports"
ADD FOREIGN KEY("id") REFERENCES "report_images"("report_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "report_images"("uploaded_by")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "municipalities"
ADD FOREIGN KEY("id") REFERENCES "reports"("municipality_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "forces"
ADD FOREIGN KEY("id") REFERENCES "reports"("force_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "sizes"
ADD FOREIGN KEY("id") REFERENCES "reports"("size_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "reports"
ADD FOREIGN KEY("id") REFERENCES "report_attachments"("report_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "report_attachments"("uploaded_by")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "reports"
ADD FOREIGN KEY("id") REFERENCES "report_reviews"("report_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "report_reviews"("reviewer_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
